spring:
    application:
        name: course-service
    
    datasource:
        url: jdbc:postgresql://localhost:5433/coursedb
        username: user
        password: password
        
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        
server:
    port: 9092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

#Actuator Properties 

management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true

info:
  app:
    name: 'course-service'
    description: 'this is course service (from git hub refreshed from bus 2)'
    version: '1.0'